name: report tests

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/report_tests.yml'
      - 'scripts/report/*.py'
      - 'scripts/report/pyproject.toml'
      - 'scripts/report/poetry.lock'
  pull_request:
    paths:
      - '.github/workflows/report_tests.yml'
      - 'scripts/report/*.py'
      - 'scripts/report/pyproject.toml'
      - 'scripts/report/poetry.lock'
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: scripts/report
        run: ./test_stack.sh